### ISSUE TITLE
Test for GCD might be wrong

### ISSUE THREAD

**Issue by MadhavJivrajani** [lord8266/test_intal#1]
If a = 0 or b = 0 but not both, shouldn't the non-zero value be returned according to Euclid's algorithm?

0 will be returned only when both a and b are 0 according to the explicit constraint provided. 

I may be wrong, please let me know :)

**Comment by lord8266** [comment]
True, gcd of 2 numbers where one of them is zero is the other but the 
header provided says
```
// Let GCD be "0" if one of intal1 and intal2 is "0".
```
so i just let it be their way

If you are referring to https://github.com/lord8266/test_intal/blob/42ff84aa24b208a0704e1caf2d714e08df91cbfa/test.py#L263
it does return 0 when either is 0

Thanks for caring to look at this code

**Comment by MadhavJivrajani** [comment]
Ah okay I see the confusion, the header file has been updated, it now says let GCD be zero if _both_ intal1 and intal2 are zero. 

Kudos on the tests, it was very helpful! :)

**Comment by lord8266** [comment]
Thanks for informing, I've updated the eval and the header

**Comment by MadhavJivrajani** [comment]
There's an issue with Fibonacci as well if I'm not wrong, fib(0) would return 1

**Comment by lord8266** [comment]
Thanks, I've fixed that
Let me know if there are more issues as well

**Comment by MadhavJivrajani** [comment]
Surely, feel free to close this issue. I'll raise another one if there's anything else. 

Thanks again for the tests :')
